plugins {
    id 'com.android.application'
}

android {
    namespace 'com.e3n.wechatfcmrefresh'
    compileSdk 35
    defaultConfig {
        applicationId 'com.e3n.wechatfcmrefresh'
        minSdk 29
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
